name: Lint

on:
  pull_request:
    paths-ignore:
    - "LICENSE"
    - "README.md"
  push:
    paths-ignore:
    - "LICENSE"
    - "README.md"

jobs:
  pod_lint:
    runs-on: macos-26
    timeout-minutes: 10

    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.app/Contents/Developer

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true

    - name: Setup ruby
      uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
      with:
        ruby-version: '4.0.1'
        bundler-cache: true

    - name: Lint swift-http-structured-headers.podspec
      run: make pod_lint

  actionlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
      with:
        reporter: github-pr-review
        level: warning
