name: Lint

on:
  pull_request:
    paths-ignore:
    - "LICENSE"
    - "README.md"
  push:
    paths-ignore:
    - "LICENSE"
    - "README.md"

jobs:
  pod_lint:
    runs-on: macos-26
    timeout-minutes: 10

    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.app/Contents/Developer

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true

    - name: Setup ruby
      uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
      with:
        ruby-version: '4.0.7'
        bundler-cache: true

    - name: Lint swift-http-structured-headers.podspec
      run: make pod_lint

  actionlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
      with:
        reporter: github-pr-review
        level: warning
